credentials:
  usernames:
    user1:
      email: user1@example.com
      name: User One
      password: pass1  # plain text, will be hashed automatically
cookie:
  expiry_days: 30
  key: some_random_key
  name: some_cookie_name
pre-authorized:
  emails: []
